# --- General options --- #
encoding: utf-8
title: gumulka.net
url-pretty: gumulka.net
url-source: https://github.com/pgum/pgum.github.io/tree/master

description: the notepad of ideas
# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
# avatar: "/img/avatar-icon.png"
# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
# title-img: /path/to/image

# --- Navigation bar options --- #
# List of links in the navigation bar
navbar-links:
  slides: "slides"
  notes: "notes"
  checklists: "notes/#checklists"
  concepts: "notes/#concepts"
  scenarios: "notes/#scenarios"

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Piotr Jacek Gumulka
  tagline: Automation enthusiast
  avatar: pjg.PNG  
  citizenship: Polish

# Select your active Social Network Links.
# Uncomment the links you want to show in the footer and add your information to each link.
# You can reorder the items to define the link order.
# If you want to add a new link that isn't here, you'll need to also edit the file _data/SocialNetworks.yml
contact:
  rss: true
  email: "pjgumulka@gmail.com"
  phone: 517 463 789
  github: pgum
  linkedin: piotr-gumulka
  youtube: turtleCalledCalmie

# Select which share links to show in posts
share-links-active:
  facebook: true
  linkedin: true

resume:
  print: false
  sidebar:
    education: true
    certs: false
    skills: true

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# Ruby Date Format
date_format: "%B %-d, %Y"

# Output options (more information on Jekyll's site)
timezone: "Europe/Warsaw"
markdown: kramdown
highlighter: rouge
#permalink: /:year-:month-:day-:title/
permalink: /:categories/:title/
paginate: 10

kramdown:
  input: GFM

collections:
 slides:
   output: true
   order: 
    - introduction.md

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: false  
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "_slides"
      type: "slides"
    values:
      layout: "reveal"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile
  - Rakefile

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189