version: '3'
services:
  jekyll:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./src:/srv/jekyll:Z
      - ./vendor/bundle:/usr/local/bundle:Z