---
- name: Copy admin.conf file from remote node to host
  hosts: cplane-0.k8s.local
  gather_facts: false

  tasks:
    - name: Fetch admin.conf 
      become: yes
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: ./admin.conf
        flat: yes    