---
- name: Set up load balancer server
  hosts: load_balanacer
  become: true
  tasks:
    - name: Disable firewalld
      service:
        name: firewalld
        state: stopped
        enabled: false
    - name: Disable SELinux in /etc/sysconfig/selinux
      replace:
        path: /etc/sysconfig/selinux
        regexp: '^SELINUX'
        replace: 'SELINUX=disabled'
    - name: Install haproxy
      yum:
        name: haproxy
        state: present
    - name: Copy haproxy.cfg to load_balancer server
      copy:
        src: ./haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: '0644'
    - name: Start and enable haproxy
      service:
        name: haproxy
        state: started
        enabled: true

