---

- name: Setup ansible maintenance user on CentOS-based servers
  hosts: centos
  become: true
  tasks:
    - name: Create user
      user:
        name: borg
        groups: wheel
        password: ''
        shell: /bin/bash
    - name: Ensure wheel group has sudo access without password
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

- name: Setup ansible maintenance user on Ubuntu-based servers
  hosts: ubuntu
  become: true
  tasks:
    - name: Create user
      user:
        name: borg
        groups: sudo
        password: ''
        shell: /bin/bash
    - name: Ensure sudo group has sudo access without password
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

- name: Copy SSH key to remote host
  hosts: all
  become: true
  tasks:
    - name: Copy SSH key
      authorized_key:
        user: borg
        state: present
        key: "{{ lookup('file', './id_rsa.pub') }}"